### ISSUE TITLE
Please include a reference to your blog post in README

### ISSUE THREAD

**Issue by CaledoniaProject** [shhnjk/PNaCl_Leaker#1]
Can you add a reference to your blog post here:
https://shhnjk.blogspot.com/2019/07/intro-to-chromes-gold-features.html

So that I can include this in my awesome-list.

**Comment by shhnjk** [comment]
Sorry, just saw this. I've edited README.md. Was this what you wanted?

**Comment by CaledoniaProject** [comment]
Yep, thanks.
